version: '3'
services:
  dev-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tbag@122
      - POSTGRES_DB=club-info-system
      - DATABASE_URL=postgresql://postgres:Tbag@122@host.docker.internal:5432/club-info-system?schema=public
    
  cis:
    image: cis
    build:
        context: .
        dockerfile: Dockerfile
    container_name: cis
    restart: on-failure
    ports:
        - 1000:1000
    env_file:
      - .env
    depends_on:
      - dev-db

